// Generated by CoffeeScript 1.6.2
(function() {
  (function($) {
    var escapeHtml;

    escapeHtml = function(chars) {
      return chars.replace(/&/g, "&amp;").replace(/"/g, "&quot;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
    };
    $.fn.matching = function(wordPat) {
      return this.text().match(wordPat);
    };
    return $.SimpleSearch = {
      Target: null,
      Form: null,
      assignSearchTarget: function(targetItems, targetSubItems) {
        return {
          items: $(targetItems),
          subItems: $(targetSubItems),
          subItemsClass: targetSubItems,
          totalNumber: $(targetItems).size(),
          matchingItems: function(word) {
            var wordPat;

            wordPat = new RegExp(word, "i");
            return this.items.filter(function(index) {
              return $(this).text().match(wordPat);
            });
          }
        };
      },
      assignSearchForm: function(KeywordFieldId, MessageAreaId, MatchingNumberAreaId, TotalNumberAreaId, ExecuteButtonId, ClearButtonId) {
        var form,
          _this = this;

        form = {
          message: $(MessageAreaId),
          keyword: $(KeywordFieldId),
          matchingNumberArea: $(MatchingNumberAreaId),
          totalNumberArea: $(TotalNumberAreaId),
          executeButton: $(ExecuteButtonId),
          clearButton: $(ClearButtonId),
          setMessage: function(word, numberOfMatchedItems) {
            this.matchingNumberArea.text(numberOfMatchedItems);
            return this.message.text(word);
          },
          clearMessage: function() {
            this.keyword.focus();
            this.keyword.select();
            return this.setMessage("", $.SimpleSearch.Target.totalNumber);
          }
        };
        form.totalNumberArea.text(this.Target.totalNumber);
        form.executeButton.click(function() {
          return _this.executeSearch();
        });
        form.clearButton.click(function() {
          return _this.clearSearch();
        });
        return form;
      },
      executeSearch: function() {
        var matchingItems, word, wordPat;

        this.Target.items.hide();
        word = escapeHtml(this.Form.keyword.val());
        matchingItems = this.Target.matchingItems(word);
        matchingItems.show();
        wordPat = new RegExp(word, "i");
        matchingItems.each(function(index) {
          var heading;

          heading = $(this).children().first();
          if (!heading.matching(wordPat)) {
            $(this).children($.SimpleSearch.Target).filter(function(index) {
              return !$(this).matching(wordPat);
            }).hide();
            return heading.show();
          }
        });
        this.Form.setMessage(word, matchingItems.size());
        return false;
      },
      clearSearch: function() {
        this.Target.items.show();
        this.Target.subItems.show();
        this.Form.clearMessage();
        return false;
      },
      setup: function(targetItems, targetSubItems, KeywordFieldId, MessageAreaId, MatchingNumberAreaId, TotalNumberAreaId, ExecuteButtonId, ClearButtonId) {
        this.Target = this.assignSearchTarget(targetItems, targetSubItems);
        this.Form = this.assignSearchForm(KeywordFieldId, MessageAreaId, MatchingNumberAreaId, TotalNumberAreaId, ExecuteButtonId, ClearButtonId);
        return this.Form.clearMessage();
      }
    };
  })(jQuery);

}).call(this);
