// Generated by CoffeeScript 1.6.2
(function() {
  (function($) {
    var escapeHtml;

    escapeHtml = function(chars) {
      return chars.replace(/&/g, "&amp;").replace(/"/g, "&quot;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
    };
    return $.SimpleSearch = {
      Target: null,
      Form: null,
      assignSearchTarget: function(targetItems) {
        return {
          items: $(targetItems),
          totalNumber: $(targetItems).size(),
          matchingItems: function(word) {
            var wordPat;

            wordPat = new RegExp(word, "i");
            return this.items.filter(function(index) {
              return $(this).text().match(wordPat);
            });
          }
        };
      },
      assignSearchForm: function(KeywordFieldId, MessageAreaId, MatchingNumberAreaId, TotalNumberAreaId, ExecuteButtonId, ClearButtonId, totalNumber) {
        var form,
          _this = this;

        form = {
          message: $(MessageAreaId),
          keyword: $(KeywordFieldId),
          matchingNumberArea: $(MatchingNumberAreaId),
          totalNumberArea: $(TotalNumberAreaId),
          executeButton: $(ExecuteButtonId),
          clearButton: $(ClearButtonId),
          setMessage: function(word, numberOfMatchedItems) {
            this.matchingNumberArea.text(numberOfMatchedItems);
            return this.message.text(word);
          },
          clearMessage: function() {
            this.keyword.focus();
            this.keyword.select();
            return this.setMessage("", totalNumber);
          }
        };
        form.totalNumberArea.text(totalNumber);
        form.executeButton.click(function() {
          return _this.executeSearch();
        });
        form.clearButton.click(function() {
          return _this.clearSearch();
        });
        return form;
      },
      executeSearch: function() {
        var matchingItems, word;

        this.Target.items.hide();
        word = escapeHtml(this.Form.keyword.val());
        matchingItems = this.Target.matchingItems(word);
        matchingItems.show();
        this.Form.setMessage(word, matchingItems.size());
        return false;
      },
      clearSearch: function() {
        this.Target.items.show();
        this.Form.clearMessage();
        return false;
      }
    };
  })(jQuery);

}).call(this);
